[package]
name = "noky-moka"
version = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
eyre = { workspace = true }
noky-store = { path = "../noky-store" }
moka = { version = "0.12", features = ["future"] }
serde = { workspace = true }