[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"
publish = false

[workspace.dependencies]
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }