[package]
name = "noky-redis"
version = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
eyre = { workspace = true }
noky-store = { path = "../noky-store" }
redis = { version = "0.29", features = ["tokio-comp"] }
serde = { workspace = true }
